### ISSUE TITLE
Execution Bytecode Problems

### ISSUE THREAD

**Issue by memes231** [SecondNewtonLaw/RbxStu#5]
![image](https://github.com/RbxStu/RbxStu/assets/87345724/54692621-2272-4b41-a343-4a9773b62056)

I'm Using LoadLibray Injector and LoadLibrary Injector Inject Successful but after i press enter Input Lua code, It does nothing. How do i fix?

**Comment by memes231** [comment]
![image](https://github.com/RbxStu/RbxStu/assets/87345724/e0535000-8fb9-4834-b4c8-c1caf710a658)

**Comment by SecondNewtonLaw** [comment]
If this happens you must input `reinit()` on the command prompt, this is because it will enable the pseudo2addr hook to get the state again, if you left game or injected before you clicked play it is likely you need to do it

**Comment by SecondNewtonLaw** [comment]
No follow up on the issue, comment when you have any updates.
